# Generated by Django 4.1.4 on 2023-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='', max_length=30)),
                ('volume', models.CharField(default='', max_length=30)),
                ('dprice', models.CharField(default='', max_length=30)),
                ('momentum', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
