# Generated by Django 4.1.4 on 2023-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0004_clientdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='stdev',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='masterdb',
            name='trend',
            field=models.CharField(default='', max_length=30),
        ),
    ]
