# Generated by Django 4.1.4 on 2023-03-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0007_masterdb_volatility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdb',
            name='volatility',
        ),
    ]
