# Generated by Django 4.1.4 on 2023-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0009_masterdb_volatility'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='momentumMean',
            field=models.CharField(default='', max_length=30),
        ),
    ]
