# Generated by Django 4.1.4 on 2023-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0011_remove_masterdb_momentummean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='selectionMenu',
            field=models.CharField(default='', max_length=30),
        ),
    ]
