# Generated by Django 4.1.4 on 2023-04-08 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0013_masterdb_analysis_masterdb_selectionmenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdb',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='masterdb',
            name='trendStdev',
        ),
    ]
