# Generated by Django 4.1.4 on 2023-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0016_rename_selectionlist_clientdata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='dpriceStdev',
            field=models.CharField(default='', max_length=30),
        ),
    ]
