# Generated by Django 4.1.4 on 2023-05-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0019_masterdb_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdata',
            old_name='timeFrame',
            new_name='timeframe',
        ),
    ]
