# Generated by Django 4.1.4 on 2023-05-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0021_raw_masterdb_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='unix',
            field=models.CharField(default='', max_length=30),
        ),
    ]
