# Generated by Django 4.1.4 on 2023-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0022_raw_unix'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='deltaT',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='masterdb',
            name='rValue',
            field=models.CharField(default='', max_length=30),
        ),
    ]
