# Generated by Django 4.1.4 on 2023-07-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0023_masterdb_deltat_masterdb_rvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSDT_PERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=30)),
                ('unix', models.CharField(default='', max_length=30)),
                ('price', models.CharField(default='', max_length=30)),
                ('volume', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
