# Generated by Django 4.1.4 on 2023-07-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0024_btcusdt_perp'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='balanceShort',
            field=models.CharField(default='', max_length=30),
        ),
    ]
