# Generated by Django 4.1.4 on 2023-08-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0029_masterdb_profit_masterdb_profit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdb',
            name='prev_trade_unix',
            field=models.CharField(default='', max_length=30),
        ),
    ]
