# Generated by Django 4.1.1 on 2022-10-12 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default='chicken', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='BUTTON_1',
            field=models.CharField(default='OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='BUTTON_2',
            field=models.CharField(default='OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='status',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
